ARG version
FROM almalinux:${version:-8}
ARG NAME="GADDAM AKHIL" \
      COURSE="DEVOPS WITH AWS" \
      TRAINER="SHIVA KUMAR" \
      DURATION="10Hrs" \
      AUTHOR="joindevops"
RUN echo "Trainer is : ${TRAINER}, vaersion is : ${version}"
CMD ["sleep","200"]      